my:
  property: hello from config server
topic:
  arn: arn:aws:sns:us-east-2:353961506820:zebramdw
secret:
  key: h8vMK1DEVSTXCi9Akb36wZjx9U5AYWB4wbxiEqo8
access:
  key: AKIAVE2N77ACJFNIVMU4
bucket:
  name: my-aws-enc-bukcet
  key: my-object-key
lang:
  en_US:
    contentid: otp-message
    value: Your otp is
  zh_CN:
    contentid: otp-message
    value: 您的验证码是
